print('\n\n Vamos te ajudar a calcular quanto de tinta você vai precisar: ')
alturaparede = float(input('\n Digite a altura da parede: '))
larguraparede = float(input('\n Digite a lagura da parede: '))
area = (alturaparede*larguraparede)
print('\n Os valores digitados foram {:.2f} metros de altura, {:.2f} metros de largura.\n\n Considerando a área total de {:.3f}m² e que cada balde pode pintar apenas 2m², \n\n serão necessários {:.2f} baldes de tintas para pintar toda a parede.\n\n' .format(alturaparede, larguraparede, area, area/2))